# -*- coding: utf-8 -*-
"""Tarea 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGRj0_D6glaRiXCs2XSDaxy3Ay0ojgb4
"""

matriz = [[1,2,3], [4,5,6], [7,8,9]]
def diagonal_principal():
  vector_diagonal = []
  for i in range(len(matriz)):
    vector_diagonal.append(matriz[i][i])
    print (vector_diagonal)
diagonal_principal()

