# -*- coding: utf-8 -*-
"""Tarea 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12p9tTHtyz761nNtoDQNf4TA6v66zOAfh
"""

import math
# Calcular litros de pintura
#esta funcion calcula los litros de pintura necesarios y los retorna redondeados, necesita dos argumentos
def calcular_pintura(a, b):
  return math.ceil(a / b)

# Solicita datos al usuario para calcular pintura
area = float(input("ingresa el area: "))
rendimiento_litro = float(input("ingresa la cantidad de metros cuadrados por litro: "))

# Calcular y mostrar resultado de pintura
litros_necesarios = calcular_pintura(area, rendimiento_litro)
print("necesitas", litros_necesarios, "litros de pintura")
print("-" * 20)

# Calcular diagonal de un rectangulo

#esta funcion de nuevo necesita 2 argumentos enteros, los cuales operará y te retornara el resultado
def calcular_diagonal(base, altura):
  return math.sqrt(base**2 + altura**2)

# Solicitar datos al usuario para calcular diagonal
base_rectangulo = float(input("ingresa la base: "))
altura_rectangulo = float(input("ingresa la altura: "))

# Calcular y mostrar resultado de la diagonal
diagonal = calcular_diagonal(base_rectangulo, altura_rectangulo)
print("la diagonal es", diagonal)
print("-" * 20)

# Calcular largo de una escalera
def largo_escalera(altura, angulo_grados):
  # Convertir angulo a radianes
  angulo_radianes = math.radians(angulo_grados)
  # Calcular largo de la escalera
  return math.ceil(altura / math.sin(angulo_radianes))

# Solicitar datos al usuario para calcular largo de escalera
altura_casa = float(input("ingresa la altura de la casa: "))
angulo_escalera = int(input("ingresa el angulo de la escalera: "))

# Validar y calcular largo de la escalera
if altura_casa > 0 and angulo_escalera > 0 and angulo_escalera < 180: # Agregada validación para angulo < 180
  largo_necesario = largo_escalera(altura_casa, angulo_escalera)
  print("el largo de la escalera es", largo_necesario)
else:
  print("el angulo o la altura son invalidos")