# -*- coding: utf-8 -*-
"""Tarea 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wIjwMTTJw2SkaoTAbgyHj7CwoWUUkova
"""

#primero imprimo un menú para el usuario
print ("Menú: a) Pizza:10, b) Hamburgesa: 8, c)Ensalada 7")
pedido_total = 0
#creo una variable para almacenar el total del pedido
while True:
  #el While True sirve para que todo el proceso que esté dentro se repita hasta que se rompa con alguna otra orden, como break en este caso
  opcion = input("Introduce la opcion (a, b, c) que desees o 0 para salir")
  match opcion:
    case "a":
      print("Has elegido la pizza")
      pedido_total += 10
    case "b":
      print("Has elegido la hamburgesa")
      pedido_total += 8
    case "c":
      print("Has elegido la ensalada")
      pedido_total += 7
    case "0":
      print(f"Tu pedido es de {pedido_total}$")
      break
    case _:
      print("Opción no válida")
      #hago un match case con los precios y opciones de cada articulo en el menú y el doy al usuario la opción de ver el precio de su pedido y para salir

#creo una lista que contiene las horas de estudio
lista = [5, 5, 5]

#defino una funcion para sumar los tiempos y realizar el promedio
def suma_tiempo():
  for i in range (len(lista)):
    prom = sum(lista) / len(lista)
  print(f"El promedio en horas es: {prom}")
  return prom

if len(lista) == 0:
  print ("No hay datos")
  #creo una condicional que marca un error si está la lista vacia

#mando a llamar la primera función y asigno el resultado a una variable
prom_horas = suma_tiempo()
#uso una funcion anonima para hacer el promedio en minutos
print("El tiempo promedio en minutos es",(lambda x,y: x * y)(prom_horas, 60))

numero = int(input("Introduce un numero: "))
#una funcion simple que define si un numero ingresado por el usuario es par o impar
def par_impar(numero):
  if numero % 2 == 0:
    print("El numero es par")
  else:
    print("El numero es impar")

par_impar(numero)