# -*- coding: utf-8 -*-
"""Tarea 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OlfXUBMNZLayfsw40ZEZ5z7cOw6Cl5Kf
"""

#Calcular Grado
def calcular_grado():
  #Le pide ingresar el grado al usuario
  grado = float(input("Ingrese la calificacion"))
  if grado >= 0.9 and grado <= 1:
    print("A")
  elif grado >= 0.8 and grado <= 0.89:
    print("B")
  elif grado >= 0.7 and grado <= 0.79:
    print("C")
  elif grado >= 0.6 and grado <= 0.69:
    print("D")
  elif grado < 0.6:
    print("F")
  else:
    print("Score incorrecto")
  #usa varios condicionales para verificar la calificacion del usuario
calcular_grado()



#Area y Volumen Cilindro
radio = float(input("Ingrese el radio"))
altura = float(input("Ingrese la altura"))
#primero le pide al usuario los datos del cilindro para luego hacer las operaciones

#defino la funcion para el area de la base del cilindro
def area_cilindro():
  a = 2*3.1416*radio*altura + 2*3.1416*radio**2
  print("area= {:.2f}".format (a))
  #le doy formato al resultado
  return a

#ahora defino la funcion para el volumen
def volumen_cilindro():
  v=3.1416*radio**2*altura
  print("volumen={:.2f}".format(v))
  #tambien le doy formato a un resultado
  return v

#mando a llamar a las funciones
area_cilindro()
volumen_cilindro()